---
services:
  digikam:
    image: lscr.io/linuxserver/digikam:latest
    container_name: digikam
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Los_Angeles
    volumes:
      - ./config:/config
      - ${MEDIA}/Photos:/Photos
    ports:
      - 3000:3000 #optional
    #restart: unless-stopped
